apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-apps
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/AmeerPB/argocd-appfiles.git
    targetRevision: HEAD
    path: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
