apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmeerPB/argocd-appfiles.git
    targetRevision: main
    path: dev/argocd/
    helm:
      values: |
        tailscale:
          url: "argocd.cat-fingers.ts.net"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
