apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: linuxserver/transmission:latest
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: transmission-storage
          mountPath: /downloads
      volumes:
      - name: transmission-storage
        persistentVolumeClaim:
          claimName: transmission-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: homelab
spec:
  selector:
    app: transmission
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP

